targets:
  $default:
    builders:
      graphql_codegen:
        options:
          schema: lib/graphql/schema.graphql
          queries_glob: lib/graphql/**/*.graphql
          output: lib/graphql/generated/graphql_api.dart
          namingSeparator: _
          scalars:
            Upload:
              type: MultipartFile
              import: package:http/http.dart
